name: build

on:
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm from .PackageManager
        uses: pnpm/action-setup@v4

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
          cache-dependency-path: .nvmrc

      # setup tfdocs2json requirements
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false
          tofu_version: 1.8.2
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'
          cache: 'true'
      - name: Install tfdocs2json
        working-directory: data/scripts/tfdocs2json
        run: |
          go install

      - name: Install dependencies
        run: pnpm install

      - name: Run Test and build
        run: |
          pnpm run test
          pnpm run check-types
          pnpm run build
