name: build

on:
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm from .PackageManager
        uses: pnpm/action-setup@v4

      - name: Use Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
          cache-dependency-path: .nvmrc

      - name: Install dependencies
        run: pnpm install

      - name: Run Test and build
        run: |
          pnpm run test
          pnpm run check-types
          pnpm run build
